### ISSUE TITLE
[Feature]: provide action defaults

### ISSUE THREAD

**Issue by lukasz-mitka** [bbonkr/next-version-proposal-action#81]
### Please describe new feature

Instead of forcing user to provide all input parameters every time embed defaults in the action itself.
Especially for `github_token`, `pr` and `*_labels`.

**Comment by lukasz-mitka** [comment]
@bbonkr would you accept a PR for this?
Not sure I'll find time to do it, but figured it's worth at least asking.

**Comment by bbonkr** [comment]
@lukasz-mitka 

I don't know how to run an action written in typescript without inputting `github.token`.

Please do as below.

> It may not be what you want, but I think this is the best method for now.

.github/workflows/test-workflow.yml:
```yaml
name: "Test workflow"

on: 
  pull_request:
    types: ["closed"]

permissions:
  contents: write
  pull-requests: write

jobs:
  next_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get next version
        uses: bbonkr/next-version-proposal-action@v1
        id: next_version_proposal
        with:
          github_token: ${{ github.token }} # 👈 Please check this out.
          pr: ${{ github.event.pull_request.number }} # 👈 Please check this out.
          major_labels: 'major,next'
          minor_labels: 'enhancement,feature'
          next_version_prefix: 'v'
  
```

The list of labels can vary from user to user, so it may be difficult to set a default.
